[project]
site_name = "DiscoPhon"
site_description = "The Phoneme Discovery Benchmark."
site_author = "CoML"
site_url = "https://benchmarks.cognitive-ml.fr/discophon/"
copyright = """
Copyright &copy; 2026 CoML
"""
nav = [
  { "Home" = "index.md" },
  { "Benchmark" = [
    "benchmark/index.md",
    "benchmark/datasets.md",
    "benchmark/phonemes.md",
    "benchmark/tasks.md",
  ] },
  { "Leaderboard" = [
    "leaderboard/index.md",
    "leaderboard/results.md",
  ] },
  { "User guide" = [
    "guide/index.md",
    "guide/prepare.md",
    "guide/evaluate.md",
    "guide/submission.md",
    "guide/baselines.md",
  ] },
  { "API reference" = ["api/index.md"] }
]
extra_javascript = [
  "javascripts/katex.js",
  "https://unpkg.com/katex@0/dist/katex.min.js",
  "https://unpkg.com/katex@0/dist/contrib/auto-render.min.js"
]
extra_css = [
  "stylesheets/extra.css",
  "https://unpkg.com/katex@0/dist/katex.min.css",
]

[project.theme]
# favicon = "assets/favicon.png"
# logo = "assets/logo.png"
language = "en"
features = [
  "content.code.annotate",
  "content.code.copy",
  "content.code.select",
  "content.footnote.tooltips",
  "content.tooltips",
  "navigation.indexes",
  "navigation.instant",
  "navigation.instant.prefetch",
  "navigation.sections",
  "navigation.top",
  "navigation.tracking",
  "search.highlight",
]

[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

[[project.extra.social]]
icon = "fontawesome/regular/file-lines"
link = "https://arxiv.org/abs/2603.18612"

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/bootphon/discophon"

[[project.extra.social]]
icon = "fontawesome/brands/python"
link = "https://pypi.org/project/discophon"

[project.plugins.mkdocstrings.handlers.python]
inventories = [
  "https://docs.python.org/3/objects.inv",
  "https://docs.xarray.dev/en/stable/objects.inv",
  "https://joblib.readthedocs.io/en/stable/objects.inv",
]

[project.plugins.mkdocstrings.handlers.python.options]
docstring_section_style = "list"
filters = "public"
line_length = 88
members_order = "source"
merge_init_into_class = true
separate_signature = true
show_overloads = false
show_root_heading = true
show_signature_annotations = true
show_source = false
show_symbol_type_heading = true
show_symbol_type_toc = true
signature_crossrefs = true
