[project]
site_name = "DiscoPhon"
site_description = "The Phoneme Discovery Benchmark."
site_author = "CoML"
site_url = "https://benchmarks.cognitive-ml.fr/discophon/"
copyright = """
Copyright &copy; 2026 CoML
"""
nav = [
  { "Home" = "index.md" },
  { "Benchmark" = [
    "benchmark/index.md",
    "benchmark/datasets.md",
    "benchmark/phonemes.md",
    "benchmark/tasks.md",
  ] },
  { "Leaderboard" = [
    "leaderboard/index.md",
  ] },
  { "Docs" = [
    "docs/index.md",
    "docs/prepare.md",
    "docs/evaluate.md",
    "docs/submission.md",
    "docs/baselines.md",
    "docs/api.md",
  ] }
]
extra_javascript = [
  "javascripts/katex.js",
  "https://unpkg.com/katex@0/dist/katex.min.js",
  "https://unpkg.com/katex@0/dist/contrib/auto-render.min.js"
]
extra_css = [
  "stylesheets/extra.css",
  "https://unpkg.com/katex@0/dist/katex.min.css",
]

[project.theme]
# favicon = "assets/favicon.png"
# logo = "assets/logo.png"
language = "en"
features = [
  "content.code.annotate",
  "content.code.copy",
  "content.code.select",
  "content.footnote.tooltips",
  "content.tooltips",
  "navigation.indexes",
  "navigation.instant",
  "navigation.instant.prefetch",
  "navigation.sections",
  "navigation.top",
  "navigation.tracking",
  "search.highlight",
]

[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to system preference"

[[project.extra.social]]
icon = "fontawesome/regular/file-lines"
link = "https://arxiv.org/abs/2603.18612"

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/bootphon/discophon"

[project.plugins.mkdocstrings.handlers.python]
inventories = [
  "https://docs.python.org/3/objects.inv",
  "https://docs.xarray.dev/en/stable/objects.inv",
]
paths = ["src"]

[project.plugins.mkdocstrings.handlers.python.options]
backlinks = "tree"
heading_level = 4
separate_signature = true
show_bases = false
show_source = false
parameter_headings = true
show_root_heading = true
show_signature_annotations = true
docstring_options = { "ignore_init_summary" = true }
docstring_section_style = "list"
# filters = "public"
inherited_members = true
merge_init_into_class = true
show_root_full_path = false
show_symbol_type_heading = true
show_symbol_type_toc = true
signature_crossrefs = true
summary = true
unwrap_annotated = true
